<?php
declare(strict_types=1);

namespace CakeDC\OracleDriver\Test\TestCase\Database\Schema;

use Cake\Database\Connection;
use Cake\Database\Schema\TableSchema;
use Cake\Datasource\ConnectionManager;
use Cake\TestSuite\TestCase;
use CakeDC\OracleDriver\Database\Driver\OraclePDO;
use CakeDC\OracleDriver\Database\Schema\OracleSchema;
use Mockery;
use PHPUnit\Framework\Attributes\DataProvider;

/**
 * Tests for Oracle-specific schema dialect features ported from the Postgres CakePHP 5 equivalents.
 *
 * Covers:
 * - describeCheckConstraints() (H1)
 * - columnDefinitionSql() (H2)
 * - constraintSql() CHECK case (H6)
 * - createTableSql() schema-qualified table names (M5)
 * - OracleCompiler comment template (H5) — via integration
 */
class OracleSchemaDialectTest extends TestCase
{
    /**
     * Helper method for skipping tests that need a real Oracle connection.
     */
    protected function _needsConnection(): void
    {
        $config = ConnectionManager::getConfig('test');
        $this->skipIf(
            !str_contains((string)($config['driver'] ?? ''), 'Oracle'),
            'Not using Oracle for test config',
        );
    }

    /**
     * Helper to create the test tables used for integration tests.
     */
    protected function _createTables(Connection $connection): void
    {
        $this->_needsConnection();

        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_articles'; EXCEPTION WHEN OTHERS THEN NULL; END;");
        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_authors'; EXCEPTION WHEN OTHERS THEN NULL; END;");

        $connection->execute(
            'CREATE TABLE schema_authors (
                "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
                "name" VARCHAR2(50) DEFAULT \'bob\',
                "bio" DATE,
                "position" NUMBER(10) DEFAULT 1,
                "created" TIMESTAMP,
                CONSTRAINT "pk_schema_authors" PRIMARY KEY ("id"),
                CONSTRAINT "unique_position" UNIQUE ("position")
            )',
        );

        $connection->execute(
            'CREATE TABLE schema_articles (
                "id" NUMBER(20) GENERATED BY DEFAULT AS IDENTITY,
                "title" VARCHAR2(20),
                "body" CLOB,
                "author_id" NUMBER(10) NOT NULL,
                "published" NUMBER(1) DEFAULT 0,
                "created" TIMESTAMP,
                CONSTRAINT "pk_schema_articles" PRIMARY KEY ("id"),
                CONSTRAINT "author_fk" FOREIGN KEY ("author_id") REFERENCES schema_authors ("id") ON DELETE SET NULL,
                CONSTRAINT "author_id_value_check" CHECK ("author_id" > 0)
            )',
        );
    }

    /**
     * Test describeCheckConstraints() returns Oracle CHECK constraints.
     */
    public function testDescribeCheckConstraints(): void
    {
        $connection = ConnectionManager::get('test');
        assert($connection instanceof Connection);
        $this->_createTables($connection);

        $dialect = $connection->getDriver()->schemaDialect();
        $checks = $dialect->describeCheckConstraints('schema_articles');

        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_articles'; EXCEPTION WHEN OTHERS THEN NULL; END;");
        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_authors'; EXCEPTION WHEN OTHERS THEN NULL; END;");

        $names = array_column($checks, 'name');
        $this->assertContains('author_id_value_check', $names);

        $check = null;
        foreach ($checks as $c) {
            if ($c['name'] === 'author_id_value_check') {
                $check = $c;
                break;
            }
        }

        $this->assertNotNull($check);
        $this->assertSame(TableSchema::CONSTRAINT_CHECK, $check['type']);
        $this->assertStringContainsString('author_id', $check['expression']);
        $this->assertStringContainsString('> 0', $check['expression']);
    }

    /**
     * Data provider for constraintSql CHECK case tests.
     */
    public static function constraintSqlCheckProvider(): array
    {
        return [
            [
                'author_id_check',
                ['type' => 'check', 'expression' => 'author_id > 0'],
                'CONSTRAINT "author_id_check" CHECK (author_id > 0)',
            ],
            [
                'salary_check',
                ['type' => 'check', 'expression' => 'salary >= 0 AND salary <= 1000000'],
                'CONSTRAINT "salary_check" CHECK (salary >= 0 AND salary <= 1000000)',
            ],
        ];
    }

    /**
     * Test constraintSql() generates correct CHECK constraint SQL.
     */
    #[DataProvider('constraintSqlCheckProvider')]
    public function testConstraintSqlCheck(string $name, array $data, string $expected): void
    {
        $driver = $this->_getMockedDriver();
        $schema = new OracleSchema($driver);

        $table = (new TableSchema('schema_articles'))
            ->addColumn('author_id', ['type' => 'integer'])
            ->addColumn('salary', ['type' => 'decimal'])
            ->addConstraint($name, $data);

        $this->assertSame($expected, $schema->constraintSql($table, $name));
    }

    /**
     * Data provider for columnDefinitionSql tests.
     */
    public static function columnDefinitionSqlProvider(): array
    {
        return [
            [
                'title',
                ['type' => 'string', 'length' => 25, 'null' => false],
                '"title" VARCHAR2(25) NOT NULL',
            ],
            [
                'body',
                ['type' => 'text', 'null' => true],
                '"body" CLOB DEFAULT NULL',
            ],
            [
                'id',
                ['type' => 'integer', 'length' => 10, 'null' => false],
                '"id" NUMBER(10) NOT NULL',
            ],
            [
                'amount',
                ['type' => 'decimal', 'length' => 12, 'precision' => 4, 'null' => true],
                '"amount" NUMBER(12,4) DEFAULT NULL',
            ],
        ];
    }

    /**
     * Test columnDefinitionSql() produces the same output as columnSql() for equivalent data.
     */
    #[DataProvider('columnDefinitionSqlProvider')]
    public function testColumnDefinitionSql(string $name, array $data, string $expected): void
    {
        $driver = $this->_getMockedDriver();
        $schema = new OracleSchema($driver);

        $table = (new TableSchema('schema_articles'))->addColumn($name, $data);
        $fromColumnSql = $schema->columnSql($table, $name);

        $data['name'] = $name;
        $fromDefinitionSql = $schema->columnDefinitionSql($data);

        $this->assertSame($expected, $fromColumnSql, 'columnSql output mismatch');
        $this->assertSame($expected, $fromDefinitionSql, 'columnDefinitionSql output mismatch');
        $this->assertSame($fromColumnSql, $fromDefinitionSql, 'columnSql and columnDefinitionSql must match');
    }

    /**
     * Test createTableSql() prefixes schema name when set in driver config.
     */
    public function testCreateTableSqlSchemaQualified(): void
    {
        $driver = $this->_getMockedDriver(['schema' => 'myschema']);
        $connection = Mockery::mock(Connection::class)->makePartial();
        $connection->shouldReceive('getWriteDriver')->andReturn($driver);

        $table = (new TableSchema('schema_articles'))->addColumn('title', [
            'type' => 'string',
            'length' => 255,
        ]);
        $sql = $table->createSql($connection);
        $this->assertStringContainsString('CREATE TABLE "myschema"."schema_articles"', $sql[0]);
    }

    /**
     * Test createTableSql() does not prefix schema when no schema is set.
     */
    public function testCreateTableSqlNoSchema(): void
    {
        $driver = $this->_getMockedDriver();
        $connection = Mockery::mock(Connection::class)->makePartial();
        $connection->shouldReceive('getWriteDriver')->andReturn($driver);

        $table = (new TableSchema('schema_articles'))->addColumn('title', [
            'type' => 'string',
            'length' => 255,
        ]);
        $sql = $table->createSql($connection);
        $this->assertStringContainsString('CREATE TABLE "schema_articles"', $sql[0]);
        $this->assertStringNotContainsString('"."schema_articles"', $sql[0]);
    }

    /**
     * Test that constraintSql handles PRIMARY, UNIQUE, and FOREIGN KEY correctly.
     */
    public function testConstraintSqlVariants(): void
    {
        $driver = $this->_getMockedDriver();
        $schema = new OracleSchema($driver);

        $table = (new TableSchema('articles'))
            ->addColumn('id', ['type' => 'integer'])
            ->addColumn('author_id', ['type' => 'integer'])
            ->addConstraint('primary', ['type' => 'primary', 'columns' => ['id']])
            ->addConstraint('unique_idx', ['type' => 'unique', 'columns' => ['author_id']])
            ->addConstraint('fk_author', [
                'type' => 'foreign',
                'columns' => ['author_id'],
                'references' => ['authors', 'id'],
                'update' => 'setNull',
                'delete' => 'cascade',
            ]);

        $this->assertSame('PRIMARY KEY ("id")', $schema->constraintSql($table, 'primary'));
        $this->assertStringContainsString('UNIQUE', $schema->constraintSql($table, 'unique_idx'));
        $this->assertStringContainsString('FOREIGN KEY', $schema->constraintSql($table, 'fk_author'));
    }

    /**
     * Test convertIndexDescription assigns primary constraint name and type separately.
     */
    public function testConvertIndexDescriptionPrimary(): void
    {
        $driver = $this->_getMockedDriver();
        $schemaDialect = new OracleSchema($driver);
        $table = (new TableSchema('articles'))->addColumn('id', ['type' => 'integer']);

        $schemaDialect->convertIndexDescription($table, [
            'name' => 'pk_articles',
            'column_name' => 'id',
            'is_primary' => 'P',
            'is_unique' => 1,
        ]);

        $this->assertSame(['id'], $table->getPrimaryKey());
        $this->assertSame(TableSchema::CONSTRAINT_PRIMARY, $table->getConstraint('primary')['type']);
    }

    /**
     * Test convertIndexDescription treats non-unique indexes as regular indexes.
     */
    public function testConvertIndexDescriptionNonUnique(): void
    {
        $driver = $this->_getMockedDriver();
        $schemaDialect = new OracleSchema($driver);
        $table = (new TableSchema('articles'))->addColumn('author_id', ['type' => 'integer']);

        $schemaDialect->convertIndexDescription($table, [
            'name' => 'author_idx',
            'column_name' => 'author_id',
            'is_primary' => null,
            'is_unique' => 0,
        ]);

        $this->assertSame('index', $table->getIndex('author_idx')['type']);
        $this->assertNull($table->getConstraint('author_idx'));
    }

    /**
     * Test convertForeignKeyDescription merges multi-column foreign keys in column order.
     */
    public function testConvertForeignKeyDescriptionMultiColumn(): void
    {
        $driver = $this->_getMockedDriver();
        $schemaDialect = new OracleSchema($driver);
        $table = (new TableSchema('articles_tags'))
            ->addColumn('article_id', ['type' => 'integer'])
            ->addColumn('tag_id', ['type' => 'integer']);

        $schemaDialect->convertForeignKeyDescription($table, [
            'column_name' => 'article_id',
            'constraint_name' => 'composite_fk',
            'referenced_owner' => 'TEST',
            'referenced_table_name' => 'articles',
            'referenced_column_name' => 'id',
            'delete_rule' => 'CASCADE',
            'deferrable' => 'NOT DEFERRABLE',
            'deferred' => 'IMMEDIATE',
        ]);
        $schemaDialect->convertForeignKeyDescription($table, [
            'column_name' => 'tag_id',
            'constraint_name' => 'composite_fk',
            'referenced_owner' => 'TEST',
            'referenced_table_name' => 'articles',
            'referenced_column_name' => 'site_id',
            'delete_rule' => 'CASCADE',
            'deferrable' => 'NOT DEFERRABLE',
            'deferred' => 'IMMEDIATE',
        ]);

        $constraint = $table->getConstraint('composite_fk');
        $this->assertSame(['article_id', 'tag_id'], $constraint['columns']);
        $this->assertSame(['TEST.articles', ['id', 'site_id']], $constraint['references']);
    }

    /**
     * Test describeForeignKeys returns composite foreign key columns in order.
     */
    public function testDescribeForeignKeysColumnOrdering(): void
    {
        $this->_needsConnection();
        $connection = ConnectionManager::get('test');
        assert($connection instanceof Connection);

        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_fk_child'; EXCEPTION WHEN OTHERS THEN NULL; END;");
        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_fk_parent'; EXCEPTION WHEN OTHERS THEN NULL; END;");
        $connection->execute(
            'CREATE TABLE schema_fk_parent (
                "id" NUMBER(10) NOT NULL,
                "site_id" NUMBER(10) NOT NULL,
                CONSTRAINT "pk_schema_fk_parent" PRIMARY KEY ("id", "site_id")
            )',
        );
        $connection->execute(
            'CREATE TABLE schema_fk_child (
                "article_id" NUMBER(10) NOT NULL,
                "tag_id" NUMBER(10) NOT NULL,
                CONSTRAINT "composite_fk" FOREIGN KEY ("article_id", "tag_id")
                    REFERENCES schema_fk_parent ("id", "site_id") ON DELETE CASCADE
            )',
        );

        $dialect = $connection->getDriver()->schemaDialect();
        $keys = $dialect->describeForeignKeys('schema_fk_child');

        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_fk_child'; EXCEPTION WHEN OTHERS THEN NULL; END;");
        $connection->execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE schema_fk_parent'; EXCEPTION WHEN OTHERS THEN NULL; END;");

        $this->assertCount(1, $keys);
        $this->assertSame(['article_id', 'tag_id'], $keys[0]['columns']);
        $this->assertSame(['id', 'site_id'], (array)$keys[0]['references'][1]);
    }

    /**
     * Build a mocked OraclePDO driver for unit tests.
     *
     * Mocks connect() so no real DB connection is attempted.
     *
     * @param array $config Additional config (e.g. ['schema' => 'myschema']).
     */
    protected function _getMockedDriver(array $config = []): OraclePDO
    {
        $this->_needsConnection();

        $driver = Mockery::mock(OraclePDO::class)
            ->makePartial()
            ->shouldAllowMockingProtectedMethods();
        $driver->__construct($config);

        $driver->shouldReceive('connect')->andReturnNull();
        $driver->shouldReceive('isAutoQuotingEnabled')->andReturn(true);
        $driver->shouldReceive('quoteIdentifier')->andReturnUsing(fn(string $id): string => '"' . str_replace('"', '', $id) . '"');
        $driver->shouldReceive('schemaValue')->andReturnUsing(function (mixed $v): string {
            if (is_bool($v)) {
                return $v ? 'TRUE' : 'FALSE';
            }

            if (is_int($v)) {
                return (string)$v;
            }

            return "'" . addslashes((string)$v) . "'";
        });
        $driver->shouldReceive('config')->andReturn(array_merge([
            'host' => 'localhost',
            'port' => '1521',
            'database' => 'xe',
            'username' => 'test',
            'password' => '',
            'schema' => '',
        ], $config));

        return $driver;
    }
}
